### ISSUE TITLE
`npm run serve` fails with latest release

### ISSUE THREAD

**Issue by danieljfarrell** [lbwa/vue-auth-boilerplate#23]
A peculiar problem, if I download v3.0.0 from `npm run serve` fails,

```bash
DJF2:vue-auth-boilerplate-3.0.0 daniel$ npm run serve
> vue-auth-boilerplate@3.0.0 serve /Users/daniel/Downloads/vue-auth-boilerplate-3.0.0
> vue-cli-service serve

 INFO  Starting development server...
fatal: not a git repository (or any of the parent directories): .git
 ERROR  Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at /Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/vue.config.js:22:12
    at Object.tap (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/webpack-chain/src/Plugin.js:25:24)
    at chainWebpack (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/vue.config.js:16:29)
    at /Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/lib/Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at Service.resolveWebpackConfig (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/lib/Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/lib/commands/serve.js:74:31)
    at Service.run (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/Users/daniel/Downloads/vue-auth-boilerplate-3.0.0/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-auth-boilerplate@3.0.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-auth-boilerplate@3.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2020-05-03T21_08_34_134Z-debug.log
```

Is there some dependence on `git`? Because if do the same using git it works!

``` bash
> git clone git@github.com:lbwa/vue-auth-boilerplate.git
> npm i
> npm run serve
```

**Comment by lbwa** [comment]
nope, this project didn't depend on `git`. A command used to get current git commit hash occurs the above error without git history when building process, but it's absolutely **optional** action.

https://github.com/lbwa/vue-auth-boilerplate/blob/87d130e9919de3a15e68e43f2d512ed0c0fe39f4/vue.config.js#L20-L24

## How to work without git

in [vue.config.js](https://github.com/lbwa/vue-auth-boilerplate/blob/87d130e9919de3a15e68e43f2d512ed0c0fe39f4/vue.config.js) delete those code:

https://github.com/lbwa/vue-auth-boilerplate/blob/87d130e9919de3a15e68e43f2d512ed0c0fe39f4/vue.config.js#L20-L24

```diff
- args.__COMMIT_HASH__ = JSON.stringify( 
-    require('child_process') 
-      .execSync('git rev-parse HEAD') 
-      .toString() 
- ) 
```

in [src/views/Home.vue](https://github.com/lbwa/vue-auth-boilerplate/blob/87d130e9919de3a15e68e43f2d512ed0c0fe39f4/src/views/Home.vue):

https://github.com/lbwa/vue-auth-boilerplate/blob/87d130e9919de3a15e68e43f2d512ed0c0fe39f4/src/views/Home.vue#L45-L48

```diff
commit: {
-     label: __COMMIT_HASH__.slice(0, 15),
-     href: `https://github.com/lbwa/vue-auth-boilerplate/commit/${__COMMIT_HASH__}`
+     label: '',
+     href: ''
},
```

**Comment by danieljfarrell** [comment]
OK, thanks so much.
